name: test

on: [push, pull_request]

jobs:

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: test
        run: |
          go version
          go test -race
